version: "3.5"
services:
  master_db:
    container_name: "master_db"
    restart: unless-stopped
    build:
      context: ./database/master
      dockerfile: Dockerfile
    env_file:
      - ./database/master/.master.env
    ports:
      - 3311:3306
    networks:
      - network_db
    volumes:
      - database_data_master:/var/lib/mysql
      - ./database/master/master.cnf:/etc/my.cnf

  slave_db1:
    container_name: "slave_db1"
    restart: unless-stopped
    build:
      context: ./database/slave
      dockerfile: Dockerfile
    env_file:
      - ./database/slave/.slave1.env
    networks:
      - network_db
    volumes:
      - database_data_slave1:/var/lib/mysql
      - ./database/slave/slave1.cnf:/etc/my.cnf

  slave_db2:
    container_name: "slave_db2"
    restart: unless-stopped
    build:
      context: ./database/slave
      dockerfile: Dockerfile
    env_file:
      - ./database/slave/.slave2.env
    networks:
      - network_db
    volumes:
      - database_data_slave2:/var/lib/mysql
      - ./database/slave/slave2.cnf:/etc/my.cnf

  nginxlb:
    container_name: "nginxlb"
    image: nginx:1.20.1
    ports:
      - 3310:3310
    depends_on:
      - master_db
      - slave_db1
      - slave_db2
      - init
    networks:
      - network_db
    volumes:
      - ./nginxlb/nginx.conf:/etc/nginx/nginx.conf:ro

  init:
    container_name: "init"
    restart: on-failure
    build:
      context: ./init
      dockerfile: Dockerfile
    depends_on:
      - master_db
      - slave_db1
      - slave_db2
    networks:
      - network_db
    volumes:
      - ./config.json:/app/config.json

networks:
  network_db:
volumes:
  database_data_master:
  database_data_slave1:
  database_data_slave2:
