version: "3.5"
services:
  master_db:
    container_name: "master_db"
    restart: unless-stopped
    build:
      context: ./database/master
      dockerfile: Dockerfile
    env_file:
      - ./database/master/.env
    ports:
      - 3306:3306
    networks:
      - network_db
    volumes:
      - database_data_master:/var/lib/mysql
      - ./database/master/config-mst.cnf:/etc/my.cnf

  slave_db1:
    container_name: "slave_db1"
    restart: unless-stopped
    build:
      context: ./database/slave
      dockerfile: Dockerfile
    env_file:
      - ./database/slave/.env
    ports:
      - 3307:3306
    networks:
      - network_db
    volumes:
      - database_data_slave1:/var/lib/mysql
      - ./database/slave/config-slv1.cnf:/etc/my.cnf

  slave_db2:
    container_name: "slave_db2"
    restart: unless-stopped
    build:
      context: ./database/slave
      dockerfile: Dockerfile
    env_file:
      - ./database/slave/.env
    ports:
      - 3308:3306
    networks:
      - network_db
    volumes:
      - database_data_slave2:/var/lib/mysql
      - ./database/slave/config-slv2.cnf:/etc/my.cnf

  init:
    container_name: "init"
    restart: on-failure
    build:
      context: ./init
      dockerfile: Dockerfile
    depends_on:
      - master_db
      - slave_db1
      - slave_db2
    networks:
      - network_db
    volumes:
      - ./config.json:/app/config.json

  nginxlb:
    container_name: "nginxlb"
    image: nginx:1.20.1
    ports:
      - 3310:3310
    volumes:
      - ./nginxlb/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - master_db
      - slave_db1
      - slave_db2
      - init
    networks:
      - network_db

networks:
  network_db:
volumes:
  database_data_master:
  database_data_slave1:
  database_data_slave2:
